//
// PartialMatches.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Partial matches of the provided search query. */

public struct PartialMatches: Codable {

    /** An array of objects, each representing a specific list member. */
    public var members: [ListMembers4]?
    /** The total number of items matching the query regardless of pagination. */
    public var totalItems: Int?

    public init(members: [ListMembers4]? = nil, totalItems: Int? = nil) {
        self.members = members
        self.totalItems = totalItems
    }

    public enum CodingKeys: String, CodingKey { 
        case members
        case totalItems = "total_items"
    }

}
