//
// UploadArchive.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Available when uploading an archive to create campaign content. The archive should include all campaign content and images. [Learn more](https://mailchimp.com/help/import-a-custom-html-template/). */

public struct UploadArchive: Codable {

    public enum ArchiveType: String, Codable { 
        case zip = "zip"
        case tarGz = "tar.gz"
        case tarBz2 = "tar.bz2"
        case tar = "tar"
        case tgz = "tgz"
        case tbz = "tbz"
    }
    /** The base64-encoded representation of the archive file. */
    public var archiveContent: String
    /** The type of encoded file. Defaults to zip. */
    public var archiveType: ArchiveType?

    public init(archiveContent: String, archiveType: ArchiveType? = nil) {
        self.archiveContent = archiveContent
        self.archiveType = archiveType
    }

    public enum CodingKeys: String, CodingKey { 
        case archiveContent = "archive_content"
        case archiveType = "archive_type"
    }

}
