//
// Forwards.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** An object describing the forwards and forward activity for the campaign. */

public struct Forwards: Codable {

    /** How many times the campaign has been forwarded. */
    public var forwardsCount: Int?
    /** How many times the forwarded campaign has been opened. */
    public var forwardsOpens: Int?

    public init(forwardsCount: Int? = nil, forwardsOpens: Int? = nil) {
        self.forwardsCount = forwardsCount
        self.forwardsOpens = forwardsOpens
    }

    public enum CodingKeys: String, CodingKey { 
        case forwardsCount = "forwards_count"
        case forwardsOpens = "forwards_opens"
    }

}
