#if !canImport(ObjectiveC)
  import XCTest

  extension CampaignTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CampaignTests = [
      ("testCampaign", testCampaign)
    ]
  }

  extension ListsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ListsTests = [
      ("testUpsertExistingWithInterestIDandName", testUpsertExistingWithInterestIDandName),
      ("testUpsertExistingWithInterestID", testUpsertExistingWithInterestID),
      ("testUpsertExistingWithoutInterestIDandName", testUpsertExistingWithoutInterestIDandName),
      ("testUpsertExistingWithoutInterestID", testUpsertExistingWithoutInterestID),
      ("testUpsertNewThenWithInterestIDandName", testUpsertNewThenWithInterestIDandName),
      ("testUpsertNewThenWithInterestID", testUpsertNewThenWithInterestID),
      ("testUpsertNewWithInterestIDandName", testUpsertNewWithInterestIDandName),
      ("testUpsertNewWithInterestID", testUpsertNewWithInterestID)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(CampaignTests.__allTests__CampaignTests),
      testCase(ListsTests.__allTests__ListsTests)
    ]
  }
#endif
