#if !canImport(ObjectiveC)
  import XCTest

  extension ContactTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContactTests = [
      ("testContactStatus", testContactStatus),
      ("testMarketingPermissions", testMarketingPermissions),
      ("testSetContactStatus", testSetContactStatus)
    ]
  }

  extension EventTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EventTests = [
      ("testInvalidEventName", testInvalidEventName),
      ("testInvalidPropertyName", testInvalidPropertyName),
      ("testValidEvent", testValidEvent)
    ]
  }

  extension MailchimpKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MailchimpKitTests = [
      ("testExample", testExample)
    ]
  }

  extension MailchimpSDKTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MailchimpSDKTests = [
      ("testAutotagging", testAutotagging),
      ("testContactRequest", testContactRequest),
      ("testEventRequest", testEventRequest),
      ("testPostBody", testPostBody),
      ("testPublicInterface", testPublicInterface),
      ("testSDKInitialize", testSDKInitialize),
      ("testTags", testTags)
    ]
  }

  extension MergeFieldTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MergeFieldTests = [
      ("testCustomMergeFieldAddress", testCustomMergeFieldAddress),
      ("testCustomMergeFieldString", testCustomMergeFieldString),
      ("testMergeFields", testMergeFields)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(ContactTests.__allTests__ContactTests),
      testCase(EventTests.__allTests__EventTests),
      testCase(MailchimpKitTests.__allTests__MailchimpKitTests),
      testCase(MailchimpSDKTests.__allTests__MailchimpSDKTests),
      testCase(MergeFieldTests.__allTests__MergeFieldTests)
    ]
  }
#endif
